param(
    [string]$IosCatalogPath = (Join-Path $PSScriptRoot '..\..\doubleTriangle\Packages\WildforceShared\Sources\WildforceShared\Resources\Localizable.xcstrings'),
    [string]$AndroidAppPath = (Join-Path $PSScriptRoot '..\app')
)

$ErrorActionPreference = 'Stop'

function Escape-Xml([string]$value) {
    if ($null -eq $value) { return '' }
    return $value.Replace('&', '&amp;').Replace('<', '&lt;').Replace('>', '&gt;').Replace('"', '&quot;').Replace("'", "\'")
}

function Resource-Name([string]$key) {
    $bytes = [System.Text.Encoding]::UTF8.GetBytes($key)
    $hash = [System.Security.Cryptography.SHA256]::HashData($bytes)
    $hex = [System.Convert]::ToHexString($hash).ToLowerInvariant()
    return "ios_catalog_$($hex.Substring(0, 16))"
}

$catalog = Get-Content -Raw $IosCatalogPath | ConvertFrom-Json -AsHashtable
$androidLocaleDirectories = @{
    'ca' = 'values-ca'; 'de' = 'values-de'; 'en' = 'values-en'; 'es' = 'values-es'
    'fr' = 'values-fr'; 'it' = 'values-it'; 'ja' = 'values-ja'; 'nl' = 'values-nl'
    'pt' = 'values-pt'; 'zh-Hans' = 'values-zh-rCN'
}

$entries = foreach ($key in ($catalog.strings.Keys | Sort-Object)) {
    $entry = $catalog.strings[$key]
    [ordered]@{
        iosKey = $key
        androidResource = Resource-Name $key
        localizations = [ordered]@{}
    }
}

if (($entries.androidResource | Select-Object -Unique).Count -ne $entries.Count) {
    throw 'A generated Android resource-name collision was detected.'
}

for ($index = 0; $index -lt $entries.Count; $index++) {
    $iosEntry = $catalog.strings[$entries[$index].iosKey]
    foreach ($locale in $iosEntry.localizations.Keys) {
        $unit = $iosEntry.localizations[$locale].stringUnit
        if ($null -ne $unit -and $null -ne $unit.value) {
            $entries[$index].localizations[$locale] = $unit.value
        }
    }
}

New-Item -ItemType Directory -Force (Join-Path $AndroidAppPath 'src\main\assets') | Out-Null
$mappingPath = Join-Path $AndroidAppPath 'src\main\assets\ios_localization_catalog.json'
[ordered]@{
    sourceCatalog = 'doubleTriangle/Packages/WildforceShared/Sources/WildforceShared/Resources/Localizable.xcstrings'
    sourceLanguage = $catalog.sourceLanguage
    generatedAt = (Get-Date).ToUniversalTime().ToString('o')
    entries = $entries | ForEach-Object { [ordered]@{ iosKey = $_.iosKey; androidResource = $_.androidResource } }
} | ConvertTo-Json -Depth 5 | Set-Content -Encoding utf8 $mappingPath

$resourceRoot = Join-Path $AndroidAppPath 'src\main\res'
$allLocales = @('base') + @($androidLocaleDirectories.Keys | Sort-Object)
foreach ($locale in $allLocales) {
    $directory = if ($locale -eq 'base') { 'values' } else { $androidLocaleDirectories[$locale] }
    $targetDirectory = Join-Path $resourceRoot $directory
    New-Item -ItemType Directory -Force $targetDirectory | Out-Null
    $targetPath = Join-Path $targetDirectory 'ios_catalog.xml'
    $lines = [System.Collections.Generic.List[string]]::new()
    $lines.Add('<?xml version="1.0" encoding="utf-8"?>')
    $lines.Add('<!-- Generated by scripts/sync-ios-localization-catalog.ps1. Do not edit manually. -->')
    $lines.Add('<resources>')
    foreach ($entry in $entries) {
        if ($locale -eq 'base') {
            $value = $entry.localizations['en']
            if ($null -eq $value) { $value = $entry.iosKey }
        } else {
            $value = $entry.localizations[$locale]
        }
        if ($null -ne $value) {
            $lines.Add("    <!-- iOS key: $(Escape-Xml $entry.iosKey) -->")
            $lines.Add("    <string name=`"$($entry.androidResource)`" formatted=`"false`">$(Escape-Xml $value)</string>")
        }
    }
    $lines.Add('</resources>')
    Set-Content -Encoding utf8 $targetPath $lines
}

Write-Output "Generated $($entries.Count) iOS catalog keys in Android resources."
